name = "UI"
license = "MIT"
licenselink = "https://github.com/site-0001/themes/blob/main/LICENSE"
description = "WebSite User Interface"
homepage = "https://kitsune.solar"
tags = ["website", "responsive", "multilingual", "mobile"]
features = ["posts", "shortcodes", "comments"]
min_version = "0.81.0"

[author]
  name = "Kitsune Solar"
  homepage = "https://kitsune.solar"
